Create people apis
planit-gcal/plan-it_spring pull request #1
Opened 2022-09-08 21:03 UTC by mustafaMari

All APIs are created and documented.

2022-09-10 11:11 UTC, Kartm commented
We have `!**/src/main/**/target/` in `.gitignore`, but still a `.jar` file was included in this PR. Let's fix it

2022-09-10 12:48 UTC, sereczeq requested changes
We cannot return backend error messages to the client. Return classic HTML error codes, and log the errors in the backend.

Change hardcoded strings to be declared on top of the class or preferably in a separate file.

2022-09-10 12:48 UTC, sereczeq commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +@CrossOrigin(origins = "http://localhost:8081")
Don't hardcode URLs, create variable in `application.properties` and use it

2022-09-10 12:48 UTC, sereczeq commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +@RequestMapping("plan-it/people")
Is it possible not to hardcode the Mapping URL and instead have a separate file with all of them saved as strings or something?

2022-09-10 12:48 UTC, sereczeq commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +        } catch (Exception e) {
I assume that in the future we will distinguish the exceptions, right?

2022-09-10 12:48 UTC, sereczeq commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +            return new ResponseEntity<>(new PeopleResponse(false, "Some Error Occurred: " + e.getMessage()), HttpStatus.INTERNAL_SERVER_ERROR);
Since the backend is going public soon, I don't think we should return exact errors to the requesting client. It can jeopardize the security of the code and give unauthorized entities insides into our code.

2022-09-10 12:48 UTC, sereczeq commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +    public ResponseEntity<Entity_Person> getPerson(@RequestParam Integer id) {
Why does `deletePerson()` take `long` as an argument but here you take `int` and convert it to `long` later? I think it should be consistent. Stick with either `int` or `long`

2022-09-10 12:48 UTC, sereczeq commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +            path = "all",
According to [rest standards documentation](https://restfulapi.net/http-methods/#get) 1.2. Example URIs the URL to Get all should not include `"all"`. It should be a plain URL, in our case `"people"`

2022-09-10 12:48 UTC, sereczeq commented on src/main/java/planit/people/preparation/DAOs/DAO_Person.java
> +public interface DAO_Person extends CrudRepository<Entity_Person, Long> {
Shouldn't the interface name be marked with "I": `IDAO_Person`?

2022-09-10 12:48 UTC, sereczeq commented on src/main/java/planit/people/preparation/Entities/Entity_Person.java
> +@Table(name = "Person")
Again hardcoded string

2022-09-10 12:48 UTC, sereczeq commented on src/main/java/planit/people/preparation/Entities/Entity_Person.java
> +    private String gender;
Why no `JsonProperty`?

2022-09-10 12:48 UTC, sereczeq commented on src/main/java/planit/people/preparation/Entities/Entity_Person.java
> +    @JsonSetter("name")
Everywhere else `JjsonProperty` is used. Is `JsonSetter` here on purpose?

2022-09-11 08:07 UTC, mustafaMari commented on src/main/java/planit/people/preparation/Entities/Entity_Person.java
> +    @JsonSetter("name")
according to https://www.logicbig.com/tutorials/misc/jackson/renaming-properties.html @JsonSetter is an old alternative to @JsonProperty. I used it by Mistake

2022-09-11 08:55 UTC, mustafaMari commented on src/main/java/planit/people/preparation/Entities/Entity_Person.java
> +    @JsonSetter("name")
@JsonProperty is mainly used in case we would like to name the displayed json attribute different from the name of the variable. so I will remove all tags where we do not have such case

2022-09-11 08:56 UTC, mustafaMari commented on src/main/java/planit/people/preparation/Entities/Entity_Person.java
> +    private String gender;
@JsonProperty is mainly used in case we would like to name the displayed json attribute different from the name of the variable. so I will remove all tags where we do not have such case

2022-09-11 08:58 UTC, mustafaMari commented on src/main/java/planit/people/preparation/DAOs/DAO_Person.java
> +public interface DAO_Person extends CrudRepository<Entity_Person, Long> {
All DAO are interfaces, so I figured the name is sufficient to suggest that, however for easier understanding I will rename the class

2022-09-11 09:07 UTC, mustafaMari commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +    public ResponseEntity<Entity_Person> getPerson(@RequestParam Integer id) {
Long is the type required for the used method so we will stick with long

2022-09-11 09:09 UTC, mustafaMari commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +            return new ResponseEntity<>(new PeopleResponse(false, "Some Error Occurred: " + e.getMessage()), HttpStatus.INTERNAL_SERVER_ERROR);
should we instead log the error internally somehow?

2022-09-11 09:13 UTC, mustafaMari commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +        } catch (Exception e) {
definitely, we will have a list of possible exceptions and handle them accordingly and the last one is the general Exception, however, for now this is enough

2022-09-11 09:22 UTC, mustafaMari commented on README.md
> +All APIs' requests, responses and attributes are documented using [Spring REST Docs MockMvc](https://docs.spring.io/spring-restdocs/docs/2.0.6.RELEASE/reference/html5/). [`People APIs.adoc` file](src
sorry for that xd

2022-09-11 09:22 UTC, mustafaMari commented on README.md
> +All APIs' requests, responses and attributes are documented using [Spring REST Docs MockMvc](https://docs.spring.io/spring-restdocs/docs/2.0.6.RELEASE/reference/html5/). [`People APIs.adoc` file](src
the package name was updated

2022-09-11 10:27 UTC, mustafaMari commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +            produces = {MediaType.APPLICATION_JSON_VALUE}
we are able to implement this with produces = .... but not with consumes since this configuration is used in Postmapping only and if it is used for others an error is returned stating that the media type is not recognized.

2022-09-11 10:53 UTC, mustafaMari commented on src/main/java/planit/people/preparation/Entities/Entity_Person.java
> +@Table(name = "Person")
this is table names, should be hardcoded

2022-09-11 11:00 UTC, mustafaMari commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +            path = "all",
I figured it would be better to use request parameter instead of path variables, but if it is  recommended to use path variables then we should do that

2022-09-11 12:25 UTC, sereczeq commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +            return new ResponseEntity<>(new PeopleResponse(false, "Some Error Occurred: " + e.getMessage()), HttpStatus.INTERNAL_SERVER_ERROR);
I think they could be stored in the database. But we need to make extra sure no loops / recursive errors are happening since that can cause huge costs

2022-09-11 17:32 UTC, mustafaMari commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +            return new ResponseEntity<>(new PeopleResponse(false, "Some Error Occurred: " + e.getMessage()), HttpStatus.INTERNAL_SERVER_ERROR);
that can be handled in the actual project, for now, we got the idea. I will mark this conversation resolved

2022-09-11 18:51 UTC, Kartm approved these changes

2022-09-12 06:14 UTC, sereczeq approved these changes
Great job!

2022-09-12 06:14 UTC, sereczeq commented on src/main/java/planit/people/preparation/APIs/API_People.java
> +            return new ResponseEntity<>(new PeopleResponse(false, "Some Internal Occurred"), HttpStatus.INTERNAL_SERVER_ERROR);
`"Some Internal **Error** Occured"` You missed a word

2022-09-12 16:57 UTC, merged